DROP TABLE IF EXISTS film_genre CASCADE;
DROP TABLE IF EXISTS likesfilms CASCADE;
DROP TABLE IF EXISTS follows CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS films CASCADE;
DROP TABLE IF EXISTS mpa CASCADE;
DROP TABLE IF EXISTS genre CASCADE;
DROP TABLE IF EXISTS feed CASCADE;
DROP TABLE IF EXISTS review_likes CASCADE;
DROP TABLE IF EXISTS reviews CASCADE;
DROP TABLE IF EXISTS film_director CASCADE;
DROP TABLE IF EXISTS directors CASCADE;

CREATE TABLE IF NOT EXISTS mpa (
    age_rating_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS films(
    film_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    description VARCHAR(200),
    releaseDate DATE NOT NULL,
    duration INTEGER CHECK (duration > 0),
    age_rating_id INTEGER REFERENCES mpa (age_rating_id)
);

CREATE TABLE IF NOT EXISTS users(
  user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  login VARCHAR(50) NOT NULL,
  email VARCHAR(100) NOT NULL,
  birthday DATE
);

CREATE TABLE IF NOT EXISTS follows(
    following_user_id BIGINT REFERENCES users (user_id) ON DELETE CASCADE,
    followed_user_id BIGINT REFERENCES users (user_id) ON DELETE CASCADE,
    status VARCHAR(50),
    PRIMARY KEY (following_user_id, followed_user_id)
);

CREATE TABLE IF NOT EXISTS likesfilms (
    film_id BIGINT REFERENCES films (film_id) ON DELETE CASCADE,
    user_id BIGINT REFERENCES users (user_id) ON DELETE CASCADE,
    PRIMARY KEY (film_id, user_id)
    );
CREATE TABLE IF NOT EXISTS genre (
     genre_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     genre_name VARCHAR(50) NOT NULL
    );

CREATE TABLE IF NOT EXISTS film_genre (
    film_id BIGINT REFERENCES films (film_id) ON DELETE CASCADE,
    genre_id INTEGER REFERENCES genre (genre_id) ON DELETE CASCADE,
    PRIMARY KEY (film_id, genre_id)
    );

CREATE TABLE IF NOT EXISTS directors (
    director_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL
    );

CREATE TABLE IF NOT EXISTS film_director (
    film_id BIGINT REFERENCES films (film_id) ON DELETE CASCADE,
    director_id INTEGER REFERENCES directors (director_id) ON DELETE CASCADE,
    PRIMARY KEY (film_id, director_id)
    );


-- UNIQUE: один пользователь оставляет не больше одного отзыва на фильм
CREATE TABLE IF NOT EXISTS reviews (
    review_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content VARCHAR(1000) NOT NULL,
    is_positive BOOLEAN NOT NULL,
    user_id BIGINT NOT NULL REFERENCES users (user_id) ON DELETE CASCADE,
    film_id BIGINT NOT NULL REFERENCES films (film_id) ON DELETE CASCADE,
    useful INTEGER NOT NULL DEFAULT 0,
    UNIQUE (user_id, film_id)
    );

CREATE TABLE IF NOT EXISTS review_likes (
    review_id BIGINT REFERENCES reviews (review_id) ON DELETE CASCADE,
    user_id BIGINT REFERENCES users (user_id) ON DELETE CASCADE,
    is_useful BOOLEAN NOT NULL,
    PRIMARY KEY (review_id, user_id)
    );

-- entity_id без внешнего ключа: указывает на фильм, пользователя или отзыв
CREATE TABLE IF NOT EXISTS feed (
    event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_timestamp BIGINT NOT NULL,
    user_id BIGINT NOT NULL REFERENCES users (user_id) ON DELETE CASCADE,
    event_type VARCHAR(10) NOT NULL CHECK (event_type IN ('LIKE', 'REVIEW', 'FRIEND')),
    operation VARCHAR(10) NOT NULL CHECK (operation IN ('ADD', 'REMOVE', 'UPDATE')),
    entity_id BIGINT NOT NULL
    );

