DROP TABLE IF EXISTS film_genre CASCADE;
DROP TABLE IF EXISTS likesfilms CASCADE;
DROP TABLE IF EXISTS follows CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS films CASCADE;
DROP TABLE IF EXISTS mpa CASCADE;
DROP TABLE IF EXISTS genre CASCADE;

CREATE TABLE IF NOT EXISTS mpa (
    age_rating_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS films(
    film_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR NOT NULL,
    description VARCHAR,
    releaseDate DATE NOT NULL,
    duration INTEGER,
    age_rating_id INTEGER REFERENCES mpa (age_rating_id)
);

CREATE TABLE IF NOT EXISTS users(
  user_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR NOT NULL,
  login VARCHAR NOT NULL,
  email VARCHAR NOT NULL,
  birthday DATE
);

CREATE TABLE IF NOT EXISTS follows(
    following_user_id INTEGER REFERENCES users (user_id) ON DELETE CASCADE,
    followed_user_id INTEGER REFERENCES users (user_id) ON DELETE CASCADE,
    status VARCHAR(50),
    PRIMARY KEY (following_user_id, followed_user_id)
);

CREATE TABLE IF NOT EXISTS likesfilms (
    film_id INTEGER REFERENCES films (film_id) ON DELETE CASCADE,
    user_id INTEGER REFERENCES users (user_id) ON DELETE CASCADE,
    PRIMARY KEY (film_id, user_id)
    );
CREATE TABLE IF NOT EXISTS genre (
    genre_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     genre_name VARCHAR(50) NOT NULL
    );

CREATE TABLE IF NOT EXISTS film_genre (
    film_id INTEGER REFERENCES films (film_id) ON DELETE CASCADE,
    genre_id INTEGER REFERENCES genre (genre_id) ON DELETE CASCADE,
    PRIMARY KEY (film_id, genre_id) -- Вот так задается двойной ключ!
    );


